# Categorizes changes to the user interface
ui:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.xaml'
      - '**/*.xaml.cs'

# Categorizes changes to the core C# application logic
core-logic:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.cs'
      - '!**/*.xaml.cs'
      - '!**/*.Tests/**/*.cs'

# Categorizes changes to the unit testing project
tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'Launchbox.Tests/**/*'

# Categorizes changes to NuGet packages or project structure
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.csproj'
      - '**/*.sln'
      - '.github/dependabot.yml'

# Categorizes changes to the GitHub Actions pipeline
github_actions:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*.yml'

# Categorizes documentation updates
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

# Tracks critical WinUI/MSIX packaging file changes
packaging:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.appxmanifest'
      - '**/*.wapproj'

# Tracks images, icons, and visual assets
assets:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.png'
      - '**/*.ico'
      - '**/*.svg'