# Categorizes changes to the user interface
ui:
  - '**/*.xaml'
  - '**/*.xaml.cs'

# Categorizes changes to the core C# application logic
core-logic:
  - '**/*.cs'
  - '!**/*.xaml.cs'
  - '!**/*.Tests/**/*.cs'

# Categorizes changes to the unit testing project
tests:
  - 'Launchbox.Tests/**/*'

# Categorizes changes to NuGet packages or project structure
dependencies:
  - '**/*.csproj'
  - '**/*.sln'
  - '.github/dependabot.yml'

# Categorizes changes to the GitHub Actions pipeline
github_actions:
  - '.github/workflows/**/*.yml'

# Categorizes documentation updates
documentation:
  - '**/*.md'
  - 'docs/**/*'

# Tracks critical WinUI/MSIX packaging file changes
packaging:
  - '**/*.appxmanifest'
  - '**/*.wapproj'

# Tracks images, icons, and visual assets
assets:
  - '**/*.png'
  - '**/*.ico'
  - '**/*.svg'