name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.csproj'
      - '**/packages.lock.json'
      - 'global.json'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore packages
        run: dotnet restore Launchbox.sln

      - name: Submit dependency snapshot
        uses: advanced-security/component-detection-dependency-submission-action@9c110eb34dee187cd9eca76a652b9f6a0ed22927 # v0.1.1
        with:
          detectorsCategories: NuGet

      - name: Dependency Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: always
          retry-on-snapshot-warnings: true
